# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Huntley
tagline:             'B.S.E Computer Engineering'
description:         'A country boy'
url:                 https://github.com/huntleja/huntleja.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              'John Huntley'
  email:             huntleja@email.sc.edu
  github:			huntleja

# Custom vars
version:             1.0.0
